//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewSoftMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE
    {
        public int CODIGO { get; set; }
        public int METRICA { get; set; }
        public int RETROALIMENTACION { get; set; }
        public int PUNTAJE { get; set; }
    
        public virtual METRICA METRICA1 { get; set; }
        public virtual RETROALIMENTACION RETROALIMENTACION1 { get; set; }
    }
}
