//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewSoftMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETROALIMENTACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETROALIMENTACION()
        {
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public int CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIEMPO_USO { get; set; }
        public string FRECUENCIA { get; set; }
        public int USUARIO { get; set; }
        public int SOFTWARE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE> DETALLE { get; set; }
        public virtual SOFTWARE SOFTWARE1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
