//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewSoftMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.Data.Entity;



    public partial class SOFTWARE
    {
        public class MovieGenreViewModel
        {
            public List<CATEGORIA> movies;
            public SelectList categoria;
            public string movieGenre { get; set; }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOFTWARE()
        {
            this.RETROALIMENTACION = new HashSet<RETROALIMENTACION>();
        }

      
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<bool> DEMO_GRATUITO { get; set; }
        public Nullable<bool> SOPORTE { get; set; }
        public Nullable<System.DateTime> AÑO { get; set; }
        public int CATEGORIA { get; set; }
        public int TIPO_LICENCIA { get; set; }
        public int TIPO_PLATAFORMA { get; set; }
        public int EMPRESA { get; set; }
    
        public virtual CATEGORIA CATEGORIA1 { get; set; }
        public virtual EMPRESA EMPRESA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETROALIMENTACION> RETROALIMENTACION { get; set; }
        public virtual TIPO_LICENCIA TIPO_LICENCIA1 { get; set; }
        public virtual TIPO_PLATAFORMA TIPO_PLATAFORMA1 { get; set; }
    }
}
